using Content.Shared._DV.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatEntryPirate : BoxContainer
{
    private const int NameMaxChars = 16;
    private const int JobMaxChars = 20;
    private static readonly Color SelectedEntryColor = Color.FromHex("#4d5478d9");
    private static readonly Color UnreadIndicatorColor = Color.FromHex("#28d93e");
    private static readonly Color ActiveIndicatorColor = Color.FromHex("#7ea2ff");

    public event Action<uint>? OnPressed;
    private uint _number;
    private Action<EventArgs>? _pressHandler;

    public NanoChatEntryPirate()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetRecipient(NanoChatRecipient recipient, uint number, bool isSelected)
    {
        // Remove old handler if it exists
        if (_pressHandler != null)
            ChatButton.OnPressed -= _pressHandler;

        _number = number;

        // Create and store new handler
        _pressHandler = _ => OnPressed?.Invoke(_number);
        ChatButton.OnPressed += _pressHandler;

        NameLabel.Text = TruncateForEntry(recipient.Name, NameMaxChars) ?? string.Empty;
        NameLabel.ToolTip = recipient.Name;

        var jobTitle = recipient.JobTitle ?? string.Empty;
        JobLabel.Text = TruncateForEntry(jobTitle, JobMaxChars) ?? string.Empty;
        JobLabel.ToolTip = jobTitle;
        JobLabel.Visible = !string.IsNullOrWhiteSpace(jobTitle);
        UnreadIndicator.Visible = recipient.HasUnread || isSelected;
        if (UnreadIndicator.PanelOverride is StyleBoxFlat indicatorStyle)
        {
            var indicatorColor = recipient.HasUnread ? UnreadIndicatorColor : ActiveIndicatorColor;
            indicatorStyle.BackgroundColor = indicatorColor;
            indicatorStyle.BorderColor = indicatorColor;
        }

        ChatButton.ModulateSelfOverride = isSelected ? SelectedEntryColor : null;
    }

    private static string? TruncateForEntry(string? value, int maxChars)
    {
        if (string.IsNullOrWhiteSpace(value))
            return null;

        if (value.Length <= maxChars)
            return value;

        if (maxChars <= 3)
            return value[..maxChars];

        return value[..(maxChars - 3)] + "...";
    }
}

