using Content.Shared._DV.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.IO;
using System.Numerics;

namespace Content.Client._Pirate.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatMessageBubblePirate : BoxContainer
{
    public static readonly Color OwnMessageColor = Color.FromHex("#1f402fd9");
    public static readonly Color OtherMessageColor = Color.FromHex("#3b4258f0");
    public static readonly Color TextColor = Color.FromHex("#e1e6f0");
    public static readonly Color ErrorColor = Color.FromHex("#cc3333");
    private bool? _previousIsOwnMessage;
    private uint? _previousMessageId;

    public event Action<uint>? OnStorePhotoPressed;

    public NanoChatMessageBubblePirate()
    {
        RobustXamlLoader.Load(this);
        MessageText.Modulate = TextColor;
        DeliveryFailedLabel.HorizontalAlignment = HAlignment.Right;
        PhotoNameLabel.ModulateSelfOverride = TextColor.WithAlpha(0.8f);
        StorePhotoButton.OnPressed += _ =>
        {
            if (_previousMessageId != null)
                OnStorePhotoPressed?.Invoke(_previousMessageId.Value);
        };
    }

    public void SetMessage(NanoChatMessage message, bool isOwnMessage)
    {
        if (MessagePanel.PanelOverride is not StyleBoxFlat style)
            return;

        // Configure message appearance
        style.BackgroundColor = isOwnMessage ? OwnMessageColor : OtherMessageColor;
        style.BorderThickness = new Thickness(0);

        // Set message content
        var hasText = !string.IsNullOrWhiteSpace(message.Content);
        MessageText.Visible = hasText;
        MessageText.Text = hasText ? FormattedMessage.EscapeText(message.Content) : string.Empty;

        var hasPhoto = message.HasPhoto;
        PhotoNameLabel.Visible = hasPhoto;
        PhotoNameLabel.Text = hasPhoto ? message.Photo.FileName : string.Empty;
        StorePhotoButton.Visible = hasPhoto && !isOwnMessage;
        StorePhotoButton.Disabled = !StorePhotoButton.Visible;
        StorePhotoButton.ToolTip = StorePhotoButton.Visible
            ? Loc.GetString("nano-chat-store-photo")
            : null;

        if (_previousMessageId != message.Id)
        {
            ApplyPhotoPreview(message);
            _previousMessageId = message.Id;
        }

        // Show delivery failed text if needed (only for own messages)
        DeliveryFailedLabel.Visible = isOwnMessage && message.DeliveryFailed;
        if (DeliveryFailedLabel.Visible)
            DeliveryFailedLabel.Modulate = ErrorColor;

        // Reorder children only when the message side changes.
        if (_previousIsOwnMessage != isOwnMessage)
        {
            // For own messages: FlexSpace -> MessagePanel -> RightSpacer
            // For other messages: LeftSpacer -> MessagePanel -> FlexSpace
            MessageContainer.RemoveAllChildren();

            if (isOwnMessage)
            {
                MessageContainer.AddChild(FlexSpace);
                MessageContainer.AddChild(MessageBox);
                MessageContainer.AddChild(RightSpacer);
            }
            else
            {
                MessageContainer.AddChild(LeftSpacer);
                MessageContainer.AddChild(MessageBox);
                MessageContainer.AddChild(FlexSpace);
            }

            _previousIsOwnMessage = isOwnMessage;
        }
    }

    private void ApplyPhotoPreview(NanoChatMessage message)
    {
        PhotoPreview.Texture = null;
        PhotoPreview.Visible = false;

        if (!message.HasPhoto)
            return;

        var data = message.Photo.ImageData is { Length: > 0 } imageData
            ? imageData
            : message.Photo.PreviewData;

        if (data is not { Length: > 0 })
            return;

        try
        {
            using var stream = new MemoryStream(data);
            PhotoPreview.Texture = Texture.LoadFromPNGStream(stream, $"nanochat-photo-{message.Id}");
            if (PhotoPreview.Texture != null)
            {
                const float maxWidth = 258f;
                const float maxHeight = 258f;
                var textureWidth = PhotoPreview.Texture.Size.X;
                var textureHeight = PhotoPreview.Texture.Size.Y;
                var scaledHeight = textureWidth > 0f
                    ? MathF.Min(maxHeight, maxWidth * textureHeight / textureWidth)
                    : 96f;
                PhotoPreview.SetSize = new Vector2(maxWidth, scaledHeight);
            }
            PhotoPreview.Visible = true;
        }
        catch
        {
            PhotoPreview.Texture = null;
            PhotoPreview.Visible = false;
        }
    }
}

