// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;
using System.IO;
using System.Numerics;

namespace Content.Client._Pirate.Photo.UI;

[GenerateTypedNameReferences]
public sealed partial class PhotoCardWindow : BaseWindow
{
    public PhotoCardWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var resourceCache = IoCManager.Resolve<IResourceCache>();
        PhotoNameLabel.FontOverride = resourceCache.NotoStack(variation: "Bold", size: 12);
        CaptionLabel.ModulateSelfOverride = Color.FromHex("#111111");

        CloseButton.OnPressed += _ => Close();
    }

    public void ShowImage(byte[] imageData)
    {
        try
        {
            using var stream = new MemoryStream(imageData);
            ImageDisplay.Texture = Texture.LoadFromPNGStream(stream);
        }
        catch
        {
            ImageDisplay.Texture = null;
        }
    }

    public void SetMetadata(string? customName, string? caption)
    {
        PhotoNameLabel.Text = customName ?? string.Empty;
        CaptionLabel.SetMessage(FormattedMessage.FromUnformatted(caption ?? string.Empty));
    }

    protected override DragMode GetDragModeFor(Vector2 _) => DragMode.Move;
}
